namespace :testing_task do
  desc "Testing some random tasks"
  task :first do
    puts "Hello"
  end

  task :second do
    puts "This is our second task"
  end

  task "third" do
    puts "Do 3 3 3"
  end
end


require "fileutils"
desc "We want to create and backup files"
task :create_files do
  10.times do
    FileUtils.touch("#{rand(100).to_s}_file.txt")
    FileUtils.mkdir("../backup") if !Dir.exist?("../backup")
  end
end

task :create_backup do
  FileUtils.mkdir("../backup/#{Time.now.strftime("%Y-%m-%d")}") if !Dir.exist?("../backup/#{Time.now.strftime("%Y-%m-%d")}")
  data = Dir.glob("*")
  data.each do |files|
    FileUtils.cp(files, "../backup/#{Time.now.strftime("%Y-%m-%d")}")
  end
end
